"""add clinical fsm and json ledger columns

Revision ID: 3ebc0dca2400
Revises: 
Create Date: 2026-06-16 14:11:23.487654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ebc0dca2400'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couple_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couple_name', sa.String(), nullable=True),
    sa.Column('partner_identifier_a', sa.String(), nullable=True),
    sa.Column('partner_identifier_b', sa.String(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('cumulative_insight', sa.Text(), nullable=True),
    sa.Column('last_commitment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_session_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_couple_profiles_id'), 'couple_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_couple_profiles_partner_identifier_a'), 'couple_profiles', ['partner_identifier_a'], unique=False)
    op.create_index(op.f('ix_couple_profiles_partner_identifier_b'), 'couple_profiles', ['partner_identifier_b'], unique=False)
    op.create_table('session_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('felt_heard', sa.Integer(), nullable=True),
    sa.Column('alinda_helpful', sa.Integer(), nullable=True),
    sa.Column('conversation_moved_forward', sa.Integer(), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['sessions.room_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_feedback_id'), 'session_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_session_feedback_room_id'), 'session_feedback', ['room_id'], unique=False)
    op.create_index('ix_session_feedback_room_role', 'session_feedback', ['room_id', 'role'], unique=False)
    op.create_table('session_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('couple_profile_id', sa.Integer(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('key_themes', sa.Text(), nullable=True),
    sa.Column('breakthrough_moments', sa.Text(), nullable=True),
    sa.Column('unresolved_threads', sa.Text(), nullable=True),
    sa.Column('emotional_arc_a', sa.Text(), nullable=True),
    sa.Column('emotional_arc_b', sa.Text(), nullable=True),
    sa.Column('relationship_dynamic', sa.Text(), nullable=True),
    sa.Column('concrete_commitment', sa.Text(), nullable=True),
    sa.Column('recommended_focus', sa.Text(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('total_escalation_events', sa.Integer(), nullable=True),
    sa.Column('total_repair_bids', sa.Integer(), nullable=True),
    sa.Column('resolution_reached', sa.Boolean(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('raw_summary', sa.Text(), nullable=True),
    sa.Column('session_started_at', sa.DateTime(), nullable=True),
    sa.Column('session_ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['couple_profile_id'], ['couple_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['sessions.room_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_insights_couple_number', 'session_insights', ['couple_profile_id', 'session_number'], unique=False)
    op.create_index(op.f('ix_session_insights_couple_profile_id'), 'session_insights', ['couple_profile_id'], unique=False)
    op.create_index(op.f('ix_session_insights_id'), 'session_insights', ['id'], unique=False)
    op.create_index(op.f('ix_session_insights_room_id'), 'session_insights', ['room_id'], unique=False)
    op.alter_column('chat_messages', 'room_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_messages', 'sender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('ix_chat_messages_room_timestamp', 'chat_messages', ['room_id', 'timestamp'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'sessions', ['room_id'], ['room_id'], ondelete='CASCADE')
    op.add_column('sessions', sa.Column('passcode_hash_a', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('passcode_hash_b', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('session_phase', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('session_started_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('session_duration_limit', sa.Integer(), nullable=False))
    op.add_column('sessions', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('end_requested_by', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('end_confirmed', sa.Boolean(), nullable=False))
    op.add_column('sessions', sa.Column('paused_until', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('stagnation_streak', sa.Integer(), nullable=False))
    op.add_column('sessions', sa.Column('repair_cycle_stage', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('behavioral_ledger_a', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('behavioral_ledger_b', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('recent_action_log', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('last_message_at_a', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('last_message_at_b', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('intake_a_submitted', sa.Boolean(), nullable=False))
    op.add_column('sessions', sa.Column('intake_b_submitted', sa.Boolean(), nullable=False))
    op.add_column('sessions', sa.Column('partner_profile_a', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('partner_profile_b', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('session_style_a', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('session_style_b', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('session_style', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('prior_session_summary', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('session_number', sa.Integer(), nullable=False))
    op.add_column('sessions', sa.Column('couple_profile_id', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('feedback_submitted_a', sa.Boolean(), nullable=False))
    op.add_column('sessions', sa.Column('feedback_submitted_b', sa.Boolean(), nullable=False))
    op.add_column('sessions', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.alter_column('sessions', 'room_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sessions', 'phase',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sessions', 'mode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sessions', 'consecutive_turns',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'action_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'target_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'resume_guidance_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'crisis_ready_a',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sessions', 'crisis_ready_b',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sessions', 'partner_typing',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('sessions', 'cooldown_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'safety_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'escalation_unresolved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sessions', 'avg_escalation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sessions', 'avg_blame',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sessions', 'avg_vulnerability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sessions', 'message_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_sessions_couple_profile_id'), 'sessions', ['couple_profile_id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'couple_profiles', ['couple_profile_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sessions', 'last_high_confidence_action')
    op.drop_column('sessions', 'short_reply_streak')
    op.drop_column('sessions', 'skill_streak')
    op.drop_column('sessions', 'turns_since_ai')
    op.drop_column('sessions', 'cooldown_exercise_index')
    op.drop_column('sessions', 'agreement_streak')
    op.drop_column('sessions', 'crisis_mode')
    op.drop_column('sessions', 'high_confidence_streak')
    op.drop_column('sessions', 'topic_repeat_count')
    op.drop_column('sessions', 'last_skill')
    op.drop_column('sessions', 'repair_resolved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('repair_resolved', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('last_skill', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('topic_repeat_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('high_confidence_streak', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('crisis_mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('agreement_streak', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('cooldown_exercise_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('turns_since_ai', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('skill_streak', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('short_reply_streak', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('last_high_confidence_action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_couple_profile_id'), table_name='sessions')
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sessions', 'message_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'avg_vulnerability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sessions', 'avg_blame',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sessions', 'avg_escalation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sessions', 'escalation_unresolved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sessions', 'safety_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'cooldown_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'partner_typing',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('sessions', 'crisis_ready_b',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sessions', 'crisis_ready_a',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sessions', 'resume_guidance_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'target_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'action_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'consecutive_turns',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'mode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sessions', 'phase',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sessions', 'room_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sessions', 'last_activity_at')
    op.drop_column('sessions', 'feedback_submitted_b')
    op.drop_column('sessions', 'feedback_submitted_a')
    op.drop_column('sessions', 'couple_profile_id')
    op.drop_column('sessions', 'session_number')
    op.drop_column('sessions', 'prior_session_summary')
    op.drop_column('sessions', 'session_style')
    op.drop_column('sessions', 'session_style_b')
    op.drop_column('sessions', 'session_style_a')
    op.drop_column('sessions', 'partner_profile_b')
    op.drop_column('sessions', 'partner_profile_a')
    op.drop_column('sessions', 'intake_b_submitted')
    op.drop_column('sessions', 'intake_a_submitted')
    op.drop_column('sessions', 'last_message_at_b')
    op.drop_column('sessions', 'last_message_at_a')
    op.drop_column('sessions', 'recent_action_log')
    op.drop_column('sessions', 'behavioral_ledger_b')
    op.drop_column('sessions', 'behavioral_ledger_a')
    op.drop_column('sessions', 'repair_cycle_stage')
    op.drop_column('sessions', 'stagnation_streak')
    op.drop_column('sessions', 'paused_until')
    op.drop_column('sessions', 'end_confirmed')
    op.drop_column('sessions', 'end_requested_by')
    op.drop_column('sessions', 'ended_at')
    op.drop_column('sessions', 'session_duration_limit')
    op.drop_column('sessions', 'session_started_at')
    op.drop_column('sessions', 'session_phase')
    op.drop_column('sessions', 'passcode_hash_b')
    op.drop_column('sessions', 'passcode_hash_a')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index('ix_chat_messages_room_timestamp', table_name='chat_messages')
    op.alter_column('chat_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_messages', 'sender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_messages', 'room_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_session_insights_room_id'), table_name='session_insights')
    op.drop_index(op.f('ix_session_insights_id'), table_name='session_insights')
    op.drop_index(op.f('ix_session_insights_couple_profile_id'), table_name='session_insights')
    op.drop_index('ix_session_insights_couple_number', table_name='session_insights')
    op.drop_table('session_insights')
    op.drop_index('ix_session_feedback_room_role', table_name='session_feedback')
    op.drop_index(op.f('ix_session_feedback_room_id'), table_name='session_feedback')
    op.drop_index(op.f('ix_session_feedback_id'), table_name='session_feedback')
    op.drop_table('session_feedback')
    op.drop_index(op.f('ix_couple_profiles_partner_identifier_b'), table_name='couple_profiles')
    op.drop_index(op.f('ix_couple_profiles_partner_identifier_a'), table_name='couple_profiles')
    op.drop_index(op.f('ix_couple_profiles_id'), table_name='couple_profiles')
    op.drop_table('couple_profiles')
    # ### end Alembic commands ###
