"""add behavioral_metrics to session_insight

Revision ID: 7dc33bfadb08
Revises: 3ebc0dca2400
Create Date: 2026-06-17 23:12:26.218643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc33bfadb08'
down_revision: Union[str, Sequence[str], None] = '3ebc0dca2400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_insights', sa.Column('behavioral_metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_insights', 'behavioral_metrics')
    # ### end Alembic commands ###
